baseURL = ""
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Mila Frerichs, Data Visualization consultant for social good"
enableEmoji = true
keywords = ["Data Visualization", "Consultant", "Data Storytelling", "Geospatial", "Maps", "visualization for social good", "non-profit", "civic advocacy"]

[languages]
  [languages.de]
  title = "Mila Frerichs, Offene Daten und Daten Visualisierung"
  weight = 2
  contentDir = "content/de"
  languageName = "Deutsch"
  [languages.en]
  contentDir = "content/en"
  languageName = "English"
  title = "Mila Frerichs, Data Visualization consultant for social good"
  weight = 1

[taxonomies]
featured = "featured"
category = "categories"

[params]
  description = "Mila Frerichs is a Data Visualization Consultant who helps civic advocacy groups improve the life of citizens with the help of Open Data. He uses the power of public open data and open source to build tools and (geospatial) data visualizations to increase transparency and accountability. He uses his software development skills for social good. "
mainSections = ["articles", "microposts"]
cloudinary_url = "https://res.cloudinary.com/civicvision/image/upload"
